apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myproxy
  name: myproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myproxy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myproxy
    spec:
      containers:
      - image: nginx:1.28.0
        name: nginx
        resources: {}
status: {}
