apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myproxy
  name: myproxy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myproxy
status:
  loadBalancer: {}
